include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - ios/Pods/**
    - ios/.symlinks/**
    - ios/Flutter/ephemeral/**
    - macos/Flutter/ephemeral/**
    - linux/flutter/ephemeral/**
    - windows/flutter/ephemeral/**

linter:
  rules:
